import "~/styles/globals.css"

import { Roboto } from "next/font/google"
import { headers } from "next/headers"

import { TRPCReactProvider } from "~/trpc/react"
import { ClipboardContextProvider } from "./context/ClipboardContext"
import { Toaster } from "react-hot-toast"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${roboto.variable}`}>
        <Toaster />
        <ClipboardContextProvider>
          <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
        </ClipboardContextProvider>
      </body>
    </html>
  )
}
