import "~/styles/globals.css"

import { Roboto, Chakra_Petch } from "next/font/google"
import { Toaster } from "react-hot-toast"
import { headers } from "next/headers"

import { TRPCReactProvider } from "~/trpc/react"
import { ClipboardContextProvider } from "./context/ClipboardContext"
import { NavContextProvider } from "./context/NavContext"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-sans",
})

const chakraPetch = Chakra_Petch({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal", "italic"],
  variable: "--font-chakraPetch",
})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${roboto.variable} ${chakraPetch.variable}`}>
        <Toaster />
        <NavContextProvider>
          <ClipboardContextProvider>
            <TRPCReactProvider headers={headers()}>
              {children}
            </TRPCReactProvider>
          </ClipboardContextProvider>
        </NavContextProvider>
      </body>
    </html>
  )
}
